globals = {
  "C_ChatInfo",
  "C_Timer",
  "CreateFrame",
  "DEFAULT_CHAT_FRAME",
  "GameTooltip",
  "GetCursorPosition",
  "GetRaidRosterInfo",
  "IsInGroup",
  "SLASH_WrongCthunPlanner1",
  "SetRaidTarget",
  "SlashCmdList",
  "UIParent",
  "UnitIsGroupAssistant",
  "UnitIsGroupLeader",
  "UnitName",
  "WCP",
}
