#!/usr/bin/env sh
rm -rf /mnt/c/Program\ Files\ \(x86\)/World\ of\ Warcraft/_classic_/Interface/AddOns/WrongCthunPlanner
cp -R src /mnt/c/Program\ Files\ \(x86\)/World\ of\ Warcraft/_classic_/Interface/AddOns/WrongCthunPlanner
